services:
  - type: web
    name: lawbridge-api
    env: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: JWT_SECRET
        value: your-jwt-secret
      - key: NODE_ENV
        value: production
    healthCheckPath: /health