name: Deploy Backend
on:
  push:
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}