name: Deploy Frontend
on:
  push:
    paths:
      - "client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}